version: "3.8"
services:
  personalwebsite:
    container_name: personalwebsite
    image: insertreponame/personal-website
    restart: unless-stopped
    environment:
      - GITHUB_AUTH_TOKEN=insertkey
    volumes:
      - type: bind
        source: ./Resume.pdf
        target: /app/public/Resume.pdf
networks:
  default:
    external:
      name: selfhost

